### ISSUE TITLE
Uneven dimensions for caster that makes it a bit blurry.

### ISSUE THREAD

**Issue by quyykk** [Adde-Endless-Sky/AES-Omnis#28]
The dimensions of the `ship/caster` sprite are uneven (259x400), which makes the sprite a bit blurry in certain circumstances. Continuous/0.9.15 adds a warning for this.

```
Warning: image "ship/caster" will be blurry since width and/or height are not even (259x400).
```

**Comment by AddeCurator** [comment]
Canvas size of images adjusted.
