### ISSUE TITLE
Hey there darcman00! How you doing? I love your mods, but I need help. I can't find anything in-game.

### ISSUE THREAD

**Issue by endlessskymodfan13** [Adde-Endless-Sky/AES-Omnis#3]
Hello! I'm a huge fan, or so I think...
I am using the latest 0.9.12: Stable release.
I think your mods are probably amazing, but I have no idea how to find content inside the game, and I don't know how to access the cheats mentioned in the Omnis mod. I added 100% of all your mods/plugins into Endless Sky at the same time, including the game makers High DPI plugin and I loaded the game, and everything seems normal. I don't notice anything different.

I don't know how to find the cheats you mention, or even any of the content, such as the plugin content that allows me to have access to all game content, if I am not mistaken. I tried reading all your readme files, but they only contain the mod description, but do not have any guide that shows how or where to find the mod related content inside the game after adding the plugin to the plugins folder. I even tried searching for an "Omnis" or "Adde" or "darc" star system but I was not successful in finding those, just in case this was the place to access the mod content or find the cheats, or cheat menu of some kind.

I even found myself tapping the ~ button to see if it would bring down a console. I pressed the escape key to see if there was a new menu in the main menu.... and nothing... I'm very confused. :(

I also wanted to thank you for being such a cool modder that updates their mods so quickly! That's just amazing! I just made this account so that I could contact you and ask you for help and also thank you, and you've already updated the mods again, which is amazing. 

I now also wanted to ask you if it is safe for me to download all of your updated mods again, and place them inside my plugins folder after deleting the old versions? Will this break my game or corrupt my save, or is it fine to just update all the mods and keep playing on my same save game file? I feel like I'm missing out on something if I don't update the mods, but then I will have to start all over, unless you say it's safe. I will make save file backups of course either way.

I'm just kind of lost and confused here and don't know what to do. I tried looking all over the place, and even made multiple different searches for "Omnis instructions" and "Adde mod help" or "Endless sky cheat mod guide" and various other searches to see if you wrote some documentation that explains how to find these things in game, but I found nothing after hours.

I finally decided to ask you for help here. I am defeated. I don't know what else to do.

Thank you for reading my feedback and questions, and have a really good day, and again thank you for making these cool mods.

p.s. I'm only using the high dpi mod + all of your mods. No other mods. The reason for this is that I don't know how safe it is to use older mods. I'm guessing that would cause a problem, and only your mods are actually recently updated. All the rest are extremely outdated. I don't know if those work perfectly fine (Is Endless Sky only of those extremely stable games that can handle all their old mods?) The reason I ask this is because I still see people listing these big lists containing extremely old mods, as if they're fine to use, which I find rather unusual, and I'm not willing to just automatically trust it right away.

Again thank you for reading. Please reply whenever you can. I am desperate for answers, but I refuse to rush you, since I hate that feeling when someone rushes me. So no pressure, but please I beg you do reply eventually. (whatever that means haha)
Have a good one.

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by endlessskymodfan13** [comment]
p.s.s. Is it a good idea, or a very bad idea to use the cutting edge "Continuous build"?
good idea or bad idea to use by itself? good idea or bad idea to use with your mods?
Just asking, sorry If I'm a pain in the butt!

**Comment by Darcman99** [comment]
Once mods are downloaded through github you need to unzip the downloaded zipped file for the game to be able to read the files. Continuous is merely the most up to date version of the game, and you can try it out by downloading [from here](https://github.com/EndlessSkyCommunity/ESLauncher2) and following the relevant instructions for proper installation. Adde is developed alongside continuous so that should be the most in-line experience. Continuous also has the added feature of allowing you to download plugins directly from the launcher.

Omnis is clear to see if installed correctly, there will be a wormhole in the system you start the game in, Irm has a system up near the Hai, Aben have some systems near Hai also, Fallen has two systems south west of FW space, the rest is spread throughout the game and is less telling. Alternatively, you can check the in-game plugin list and see if the game recognises any plugins installed.

You are not a pain at all, I encourage people to ask for help when needed. Please update on whether or not this issue has been resolved.

**Comment by endlessskymodfan13** [comment]
Darcman99 you are SUCH A COOL PERSON! WOW! seriously, just, wow. You're a great modder too. I really appreciate your help! Thank you! I'm gonna grab continuous, redownload all your mods since they've all been updated, and try it out and let you know if at the very least Omnis is functioning properly (because that's the only one I am 100% guaranteed to find... lol) Eventually If I am able to find the others, I may update you some more on that, but right now I will try to focus on Omnis so that at the very least I can deliver you a quick answer on that. I'm so excited to try this now! I will probably update here to let you know if found the wormhole, and whether or not I was able to go through it, and also if everything inside worked fine. I hope that it will also help you somehow with the modding process. I guess the least useful answer I could possible give is "everything works totally fine" haha but hey we will see.

**Comment by endlessskymodfan13** [comment]
Okay I found the wormhole! I really like the presentation of everything inside! It's extremely easy to see it all and navigate it. It's really beautiful and efficient actually!


*spoiler alert for anyone who doesn't know yet*

*spoiler alert for anyone who doesn't know yet*

*spoiler alert for anyone who doesn't know yet*


Everything inside seems to work fine, which is really cool. The only few things I'm confused about is that some ships require licenses, but there does not appear to be a location where the player can just simply purchase all the licenses at once.
Do you know the save game file names for all the existing licenses, and the correct location inside the save file where they should be placed?

Some people on steam suggested this:

https://steamcommunity.com/app/404410/discussions/0/492378806385329385/

SeanCannery said:
Functionality is present in game, but there is no way to get one legitimately. If you're willing to cheat a little, you can edit your savefile to give yourself the license. Will repost the instructions here; You'll need to edit your save file, which is fairly simple. First, go to C:\Users\[UserName]\AppData\Roaming\endless-sky\saves. From there, select any save you want. Open it in notepad or a text editor, and search for "License". You'll find a line of code which should say "License: Pilot's". Insert the following lines of code straight below;
"license: Carrier"
"license: Cruiser"
"license: Navy"
And that should give you access to every Republic ship, provided that you're early enough in the game that the shipyard that sell carriers haven't been "destroyed"

If this is accurate, do you know a list of all licenses in the game, and their correct names? I will possibly attempt to do this if I know them all.

I saw a discussion somewhere else where people suggested installing the all content plugin 
(I think made by the maker of the game) 
https://github.com/endless-sky/all-content-plugin 
(but I don't know if it is safe to use at the same time as your Omnis plugin since it's also an all content mod, and I also don't know if it's heavily outdated, yet still listed?)

Do the ships in the wormhole respawn after being taken? Would this technically allow the player to take a ship, then leave, return, and take another until satisfied with theoretically 100 of the same ship, even if they never had the license in the first place?

When first using any of the first four stations, it mentions taking the chip with money, but if the player takes it, the credits glitch out and turn into random numbers and letters and symbols. I simply avoided taking the chip on my next try, (I don't know what those "consequences" the chip mentions may be....) and I edited my save file so that there were 10 number 8's in a row, which should last me a while, and did not glitch out the counter.

**Comment by Darcman99** [comment]
That credit chip mission doesn't glitch anything out, that's simply how the game presents the highest possible credit value, as if you have unlimited money. As for obtaining the licenses, there is a job on the job board which gives you every license in the game.

The ship you can spawn by demanding tribute can be respawned by relinquishing tribute, landing somewhere and then tributing again. Those ships are there to test out ship builds for finding an optimal setup or otherwise testing balance when creating plugins.

**Comment by endlessskymodfan13** [comment]
I just started to understand your link to the ES launcher. I unfortunately am in a situation where I must rely on manually installing plugins by downloading the file and placing them in the correct place, and will likely never be able to take advantage of the features that require connecting the computer the game runs on to the internet. I hope that manual plugin installation will always be an option or I fear that I will one day simply be unable to use all mods, permanently. :(

**Comment by Darcman99** [comment]
It will be, this is where I host Adde plugins and that will not change, the plugins will always be able to be downloaded through github.

**Comment by Darcman99** [comment]
Closing due to the issue being resolved.

**Comment by endlessskymodfan13** [comment]
OH wow you're fast! I didn't see that post just now. I did not see that job board thing. I will test it out now! :)

*"The ship you can spawn by demanding tribute can be respawned by relinquishing tribute, landing somewhere and then tributing again. Those ships are there to test out ship builds for finding an optimal setup or otherwise testing balance when creating plugins."*
I don't know what this means, but I will see if this is also another job board related thing. I will be right back.

**Comment by endlessskymodfan13** [comment]
Oh, I wasn't aware you were closing the issue. I mean, you don't have to close it just yet... do you? I feel like indiana jones grabbing my hat under the closing rock door lol. my awkward timing huh. lol.

**Comment by endlessskymodfan13** [comment]
But hey just in case this whole thing closes and I don't get to talk to you again, Thank you!

**Comment by Darcman99** [comment]
Closed due to the issue being resolved, it's a matter of marking the issue resolved. Not closed to end a conversation, however it would be preferable to have conversations elsewhere (e.g. discord).

Demanding tribute refers to hailing one of the ship planets you see in the Omnis system, and demanding tribute.

**Comment by endlessskymodfan13** [comment]
Unfortunately if I try to use twitch or discord, my computer gets so hot that I can cook eggs on it and then it makes scary noises and crashes. I don't know why some websites do that to my computer... I try to avoid, for the sake of prolonging the lifespan of the hardware.... so I guess this is the only way I can communicate with you. I apologize since it's not the most convenient.
I will try out those things you said and let you know if it's functional! :)

**Comment by endlessskymodfan13** [comment]
Okay so good news, the license mission was 100% functional, but I overheard some people mention a world ship license, but I do not believe I received a world ship license. I don't know if that's just an assumption on the part of other people in an old reddit or steam thread I read the other day. I'm just saying, I didn't see that in there, but I guess it doesn't matter, probably. I accepted the mission from one of the stations/wormholes inside the wormhole and then landed again and it worked. It's cool that it's possible to remove them too, if the player wants. I guess I will say thanks again and goodbye for now. Thank you for your help. I may come back another time and report on any interesting issues I find, if it helps improve the mods. Have a very nice day! :)
